CeldasLibres/celdas_libres/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import CrearUsuario, ModificarUsuario, VerUsuarios, EliminarUsuario
from .forms import LoginForm

# Aca van todas las rutas de las cuentas
urlpatterns = [
    path('signup/', CrearUsuario.as_view(), name='signup'),
    path('login/', LoginView.as_view(
        template_name='accounts/login.html', authentication_form=LoginForm
        ),
        name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('modificar-usuario/<int:pk>', ModificarUsuario.as_view(), name='modificar-usuario'),
    path('usuarios/', VerUsuarios.as_view(), name='usuarios'),
    path('eliminar-usuario/<int:pk>', EliminarUsuario.as_view(), name='eliminar-usuario'),
]

CeldasLibres/celdas_libres/celdas_libres/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from core import views as core_views
from django.urls import path, include

urlpatterns = [
    path('', core_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('parqueaderos/', include('parqueaderos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CeldasLibres/celdas_libres/parqueaderos/urls.py
from django.urls import path

from .views import CrearTarifa, VerTarifas, CrearEntradaVehiculo, VerIngresados, ModificarTarifa, EliminarTarifa

urlpatterns = [
    path('crear_tarifa/', CrearTarifa.as_view(), name='crear_tarifa'),
    path('tarifas/', VerTarifas.as_view(), name='tarifas'),
    path('ingresar-vehiculo/', CrearEntradaVehiculo.as_view(), name='ingresar-vehiculo'),
    path('vehiculos-ingresados/', VerIngresados.as_view(), name='vehiculos-ingresados'),
    path('modificar-tarifa/<int:pk>', ModificarTarifa.as_view(), name='modificar-tarifa'),
    path('eliminar-tarifa/<int:pk>', EliminarTarifa.as_view(), name='eliminar-tarifa'),
]

CeldasLibres/celdas_libres/parqueaderos/models.py
from datetime import datetime
from django.db import models

def default_id():
    return datetime.now().year

class Tarifa(models.Model):
    anno = models.PositiveIntegerField(default=default_id, verbose_name="año")
    tipo_vehiculo = models.CharField(max_length=10)
    por_hora = models.PositiveIntegerField()

    class Meta:
        unique_together = (('anno', 'tipo_vehiculo'),)
        verbose_name =  'tarifa'
        ordering = ['anno']

    def __str__(self):
        #+ ' ' + str(self.anno) + ' por ' + str(self.por_hora) + ' h'
        return str(self.tipo_vehiculo).capitalize()

class EntradaVehiculo(models.Model):
    tarifa = models.ForeignKey(Tarifa, on_delete=models.SET_NULL, null=True)
    fecha_ingreso = models.DateTimeField(auto_now_add=True)
    placa = models.CharField(max_length=6)

    class Meta:
        unique_together = (('placa', 'fecha_ingreso'),)
        verbose_name =  'entrada vehiculo'
        ordering = ['fecha_ingreso']

    def __str__(self):
        return str(self.placa)

CeldasLibres/celdas_libres/parqueaderos/forms.py
from django import forms
from .models import Tarifa, EntradaVehiculo


class CrearTarifaForm(forms.ModelForm):
    tipo_vehiculo = forms.ChoiceField(
        choices=[
            ('carro', 'Carro'),
            ('moto', 'Moto'),
        ],
    )

    class Meta:
        model = Tarifa
        fields = '__all__'
        widgets = {
            'anno': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                    'readonly': True
                }
            ),
            'tipo_vehiculo': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            ),
            'por_hora': forms.NumberInput(
                attrs={
                    'class': 'form-control'
                }
            )
        }


class EntradaVehiculoForm(forms.ModelForm):
    tarifa=forms.ModelChoiceField(queryset=Tarifa.objects.all())
    placa=forms.CharField(max_length=6)
    class Meta:
        model = EntradaVehiculo
        fields = '__all__'
        widgets = {
            'tarifa': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            )
        }

CeldasLibres/celdas_libres/parqueaderos/views.py
from datetime import datetime

from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from .models import Tarifa, EntradaVehiculo
from .forms import CrearTarifaForm, EntradaVehiculoForm
from django.contrib import messages


@method_decorator([login_required, staff_member_required], name='dispatch')
class CrearTarifa(CreateView):
    model = Tarifa
    template_name = 'parqueaderos/crear_tarifa.html'
    form_class = CrearTarifaForm
    success_url = reverse_lazy('tarifas')
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            messages.success(request, 'Tarifa creada')
        return super(CrearTarifa, self).post(request, kwargs)

    def post(self, request, *args, **kwargs):
        anno = request.POST.get('anno')
        tipo_vehiculo = request.POST.get('tipo_vehiculo')
        for tarifa in Tarifa.objects.all():
            if (tarifa.anno, tarifa.tipo_vehiculo) == (int(anno), tipo_vehiculo):
                tarifa.delete()
        return super(CrearTarifa, self).post(request, *args, **kwargs)

@method_decorator([login_required], name='dispatch')
class VerTarifas(ListView):
    model = Tarifa
    context_object_name = 'tarifas_list'
    template_name = 'parqueaderos/tarifas.html'

@method_decorator([login_required, staff_member_required], name='dispatch')
class ModificarTarifa(UpdateView):
    model = Tarifa
    form_class = CrearTarifaForm
    template_name_suffix = '_update_form'
    success_url =  reverse_lazy('tarifas')

@method_decorator([login_required, staff_member_required], name='dispatch')
class EliminarTarifa(DeleteView):
    model = Tarifa
    success_url = reverse_lazy('tarifas')

@method_decorator([login_required], name='dispatch')
class CrearEntradaVehiculo(CreateView):
    model = EntradaVehiculo
    template_name = 'parqueaderos/ingresar_vehiculo.html'
    form_class = EntradaVehiculoForm
    success_url = reverse_lazy('vehiculos-ingresados')
    context_object_name = 'tarifas_list'


    def get_context_data(self, **kwargs):
        context = super(CrearEntradaVehiculo, self).get_context_data(**kwargs)
        context['tarifas'] = Tarifa.objects.filter(anno=datetime.now().year)
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            messages.success(request, 'Vehículo ingresado')
        return super(CrearEntradaVehiculo, self).post(request, kwargs)


@method_decorator([login_required], name='dispatch')
class VerIngresados(ListView):
    model = EntradaVehiculo
    context_object_name = 'ingresados_list'
    template_name = 'parqueaderos/ingresados_list.html'

CeldasLibres/celdas_libres/templates/parqueaderos/crear_tarifa.html
{% extends 'base.html' %}

{% block title %}Crear tarifa{% endblock title %}

{% block content %}
  <div class="container">
    <div class="card card-register mx-auto mt-5">
      <div class="card-header">Ingreso de Tarifas</div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="Pnombre">Año</label>
            {{ form.anno }}
          </div>
          <div class="form-group">
            <label for="Pnombre">Tipo vehiculo</label>
            {{ form.tipo_vehiculo }}
          </div>
          <div class="form-group">
            <label for="Papell">Precio hora</label>
            {{ form.por_hora }}
          </div>
          {% if form.errors %}
              {% for field in form %}
                  {% for error in field.errors %}
                      <div class="card border-danger mb-3">
                          <div class="card-body text-danger">
                              <p class="card-text">
                                  {{ error|escape }}
                              </p>
                          </div>
                      </div>
                  {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                  <div class="card border-danger mb-3">
                      <div class="card-body text-danger">
                          <p class="card-text">
                              {{ error|escape }}
                          </p>
                      </div>
                  </div>
              {% endfor %}
          {% endif %}
          <button type="submit" class="btn btn-warning btn-block">Crear tarifa</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

CeldasLibres/celdas_libres/templates/parqueaderos/ingresados_list.html
{% extends 'base.html' %}

{% block title %}Tarifas{% endblock title %}

{% block content %}
<div class="container pt-5 mt-3">
    <table class="table table-secondary table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Placa</th>
                <th scope="col">Fecha ingreso</th>
                <th scope="col">Tarifa aplicable</th>
            </tr>
        </thead>
        <tbody>
            {% for ingresado in ingresados_list %}
                <tr>
                    <th scope="row">{{ ingresado.placa }}</th>
                    <td>{{ ingresado.fecha_ingreso }}</td>
                    <td>{{ ingresado.tarifa }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

CeldasLibres/celdas_libres/templates/parqueaderos/ingresar_vehiculo.html
{% extends 'base.html' %}

{% block title %}Ingresar Vehiculo{% endblock title %}

{% block content %}
  <div class="container">
    <div class="card card-register mx-auto mt-5">
      <div class="card-header">Ingreso de vehiculo al parqueadero</div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %}
          <div class="row justify-content-center">
            <div class="col-md-6">
              <div class="form-group">
                <label for="Pnombre">Placa</label>
                {{ form.placa }}
              </div>
              <div class="form-group">
                <label for="Pnombre">Tipo vehículo</label>
                <select name="tarifa" required="" id="id_tarifa">
                    {% for tarifa in tarifas %}
                        <option value="{{ tarifa.id }}">{{ tarifa }}</option>
                    {% endfor %}
                </select>
              </div>
            </div>
            <div class="col-md-6">
              <table class="table table-secondary table-striped">
                <thead class="thead-dark">
                  <tr>
                      <th scope="col">Tipo vehiculo</th>
                      <th scope="col">Precio por hora</th>
                    </tr>
                </thead>
                <tbody>
                  {% for tarifa in tarifas %}
                      <tr>
                          <td>{{ tarifa.tipo_vehiculo }}</td>
                          <td>{{ tarifa.por_hora }}</td>
                      </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>

          {% if form.errors %}
              {% for field in form %}
                  {% for error in field.errors %}
                      <div class="card border-danger mb-3">
                          <div class="card-body text-danger">
                              <p class="card-text">
                                  {{ error|escape }}
                              </p>
                          </div>
                      </div>
                  {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                  <div class="card border-danger mb-3">
                      <div class="card-body text-danger">
                          <p class="card-text">
                              {{ error|escape }}
                          </p>
                      </div>
                  </div>
              {% endfor %}
          {% endif %}
          <button type="submit" class="btn btn-warning btn-block">Ingresar vehiculo</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

CeldasLibres/celdas_libres/templates/parqueaderos/tarifa_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="card card-register mx-auto mt-5">
      <div class="card-header">Eliminar de tarifa</div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %}
          <p>¿Esta seguro de que desea eliminar la tarifa "{{ object }}"?</p>
          <button type="submit" class="btn btn-warning btn-block">Eliminar</button>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

CeldasLibres/celdas_libres/templates/parqueaderos/tarifa_update_form.html
{% extends 'base.html' %}

{% block title %}Modificar tarifa{% endblock title %}

{% block content %}
  <div class="container">
    <div class="card card-register mx-auto mt-5">
      <div class="card-header">Ingreso de Tarifas</div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="Pnombre">Año</label>
            {{ form.anno }}
          </div>
          <div class="form-group">
            <label for="Pnombre">Tipo vehiculo</label>
            {{ form.tipo_vehiculo }}
          </div>
          <div class="form-group">
            <label for="Papell">Precio hora</label>
            {{ form.por_hora }}
          </div>
          {% if form.errors %}
              {% for field in form %}
                  {% for error in field.errors %}
                      <div class="card border-danger mb-3">
                          <div class="card-body text-danger">
                              <p class="card-text">
                                  {{ error|escape }}
                              </p>
                          </div>
                      </div>
                  {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                  <div class="card border-danger mb-3">
                      <div class="card-body text-danger">
                          <p class="card-text">
                              {{ error|escape }}
                          </p>
                      </div>
                  </div>
              {% endfor %}
          {% endif %}
          <button type="submit" class="btn btn-warning btn-block">Modificar tarifa</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

CeldasLibres/celdas_libres/templates/parqueaderos/tarifas.html
{% extends 'base.html' %}

{% block title %}Tarifas{% endblock title %}

{% block content %}
<div class="container pt-5 mt-3">
    <table class="table table-secondary table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Año</th>
                <th scope="col">Tipo vehiculo</th>
                <th scope="col">Precio por hora</th>
                {% if user.is_staff %}
                <th scope="col">Modificar</th>
                <th scope="col">Eliminar</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for tarifa in tarifas_list %}
                {% now "Y" as current %}
                {% ifequal tarifa.anno|stringformat:'i' current %}
                <tr>
                    <th scope="row">{{ tarifa.anno }}</th>
                    <td>{{ tarifa.tipo_vehiculo }}</td>
                    <td>{{ tarifa.por_hora }}</td>
                    {% if user.is_staff %}
                    <td>
                        <a href="{% url 'modificar-tarifa' tarifa.id %}">Modificar</a>
                    </td>
                    <td>
                        <a href="{% url 'eliminar-tarifa' tarifa.id %}">Eliminar</a>
                    </td>
                    {% endif %}
                </tr>
                {% endifequal %}
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}